quiet: False
keeptree: True
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"
outpkg: mocks
packages:
  github.com/haguru/horus/pkg/interfaces:
    interfaces:
      Client: