name: horus
services:
  crumbdb_service:
    command: /crumbdb
    container_name: crumb_service
    depends_on:
      - crumbdb
      - consul
    hostname: crumb_service
    image: haguru/crumbdb:0.0.0-dev
    ports:
      - 50051:50051
  crumbdb:
    image: mongodb/mongodb-community-server:latest
    # ports:
    #   - 50052:27017
  useracct_service:
    command: /useracct
    container_name: useracct_service
    depends_on:
      - useracctdb
      - consul
    hostname: useracct_service
    image: haguru/useracct:0.0.0-dev
    ports:
      - 50053:50053
  useracctdb:
    image: mongodb/mongodb-community-server:latest
    # ports:
    #   - 50054:27017
  follower_service:
    command: /follower
    container_name: follower_service
    depends_on:
      - followerdb
      - consul
    hostname: follower_service
    image: haguru/follower:0.0.0-dev
    ports:
      - 50055:50055
      - 52112:52112
  followerdb:
    image: mongodb/mongodb-community-server:latest
    # ports:
    #   - 50056:27017
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
  consul:
    image: hashicorp/consul:latest
    ports:
      - 8500:8500
