name: crumbdb
loglevel: debug
database:
  host: localhost #mongodb://localhost:27017/?maxPoolSize=20&w=majority
  port: 27017
  name: horus
  collection: crumbs
  options:
    setstrict: true
    setdeprecationerrors: true
    
