// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: useracct.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserAcctDB_Create_FullMethodName         = "/useracctdb.UserAcctDB/Create"
	UserAcctDB_GetUser_FullMethodName        = "/useracctdb.UserAcctDB/GetUser"
	UserAcctDB_UpdatePassword_FullMethodName = "/useracctdb.UserAcctDB/UpdatePassword"
	UserAcctDB_Delete_FullMethodName         = "/useracctdb.UserAcctDB/Delete"
)

// UserAcctDBClient is the client API for UserAcctDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserAcctDBClient interface {
	Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*Id, error)
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	UpdatePassword(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*Status, error)
	Delete(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Status, error)
}

type userAcctDBClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAcctDBClient(cc grpc.ClientConnInterface) UserAcctDBClient {
	return &userAcctDBClient{cc}
}

func (c *userAcctDBClient) Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*Id, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Id)
	err := c.cc.Invoke(ctx, UserAcctDB_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAcctDBClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserAcctDB_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAcctDBClient) UpdatePassword(ctx context.Context, in *PasswordRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, UserAcctDB_UpdatePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAcctDBClient) Delete(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, UserAcctDB_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAcctDBServer is the server API for UserAcctDB service.
// All implementations must embed UnimplementedUserAcctDBServer
// for forward compatibility.
type UserAcctDBServer interface {
	Create(context.Context, *User) (*Id, error)
	GetUser(context.Context, *UserRequest) (*User, error)
	UpdatePassword(context.Context, *PasswordRequest) (*Status, error)
	Delete(context.Context, *UserRequest) (*Status, error)
	mustEmbedUnimplementedUserAcctDBServer()
}

// UnimplementedUserAcctDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAcctDBServer struct{}

func (UnimplementedUserAcctDBServer) Create(context.Context, *User) (*Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserAcctDBServer) GetUser(context.Context, *UserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserAcctDBServer) UpdatePassword(context.Context, *PasswordRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (UnimplementedUserAcctDBServer) Delete(context.Context, *UserRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserAcctDBServer) mustEmbedUnimplementedUserAcctDBServer() {}
func (UnimplementedUserAcctDBServer) testEmbeddedByValue()                    {}

// UnsafeUserAcctDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAcctDBServer will
// result in compilation errors.
type UnsafeUserAcctDBServer interface {
	mustEmbedUnimplementedUserAcctDBServer()
}

func RegisterUserAcctDBServer(s grpc.ServiceRegistrar, srv UserAcctDBServer) {
	// If the following call pancis, it indicates UnimplementedUserAcctDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAcctDB_ServiceDesc, srv)
}

func _UserAcctDB_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAcctDBServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAcctDB_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAcctDBServer).Create(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAcctDB_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAcctDBServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAcctDB_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAcctDBServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAcctDB_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAcctDBServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAcctDB_UpdatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAcctDBServer).UpdatePassword(ctx, req.(*PasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAcctDB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAcctDBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAcctDB_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAcctDBServer).Delete(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAcctDB_ServiceDesc is the grpc.ServiceDesc for UserAcctDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAcctDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "useracctdb.UserAcctDB",
	HandlerType: (*UserAcctDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserAcctDB_Create_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserAcctDB_GetUser_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _UserAcctDB_UpdatePassword_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserAcctDB_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "useracct.proto",
}
