// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: routegrpc.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Crumb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location     *Point `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	User         string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Messagecrumb string `protobuf:"bytes,4,opt,name=messagecrumb,proto3" json:"messagecrumb,omitempty"`
}

func (x *Crumb) Reset() {
	*x = Crumb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routegrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Crumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crumb) ProtoMessage() {}

func (x *Crumb) ProtoReflect() protoreflect.Message {
	mi := &file_routegrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crumb.ProtoReflect.Descriptor instead.
func (*Crumb) Descriptor() ([]byte, []int) {
	return file_routegrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Crumb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Crumb) GetLocation() *Point {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Crumb) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Crumb) GetMessagecrumb() string {
	if x != nil {
		return x.Messagecrumb
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []float64 `protobuf:"fixed64,1,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Type        string    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routegrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_routegrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_routegrpc_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Point) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routegrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_routegrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_routegrpc_proto_rawDescGZIP(), []int{2}
}

func (x *Id) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routegrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_routegrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_routegrpc_proto_rawDescGZIP(), []int{3}
}

func (x *Status) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_routegrpc_proto protoreflect.FileDescriptor

var file_routegrpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x64, 0x62, 0x22, 0x7b, 0x0a, 0x05, 0x43, 0x72,
	0x75, 0x6d, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x64, 0x62, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x63, 0x72,
	0x75, 0x6d, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x22, 0x3d, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x1a, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0xaa, 0x01, 0x0a, 0x07, 0x43, 0x72, 0x75, 0x6d, 0x62, 0x44, 0x42, 0x12, 0x25,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62,
	0x64, 0x62, 0x2e, 0x43, 0x72, 0x75, 0x6d, 0x62, 0x1a, 0x0b, 0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62,
	0x64, 0x62, 0x2e, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x72, 0x75, 0x6d,
	0x62, 0x73, 0x12, 0x0e, 0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x64, 0x62, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x1a, 0x0e, 0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x64, 0x62, 0x2e, 0x43, 0x72, 0x75,
	0x6d, 0x62, 0x30, 0x01, 0x12, 0x25, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e,
	0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x64, 0x62, 0x2e, 0x43, 0x72, 0x75, 0x6d, 0x62, 0x1a, 0x0b,
	0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x64, 0x62, 0x2e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0b, 0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x64, 0x62, 0x2e,
	0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x63, 0x72, 0x75, 0x6d, 0x62, 0x64, 0x62, 0x2e, 0x49, 0x64, 0x42,
	0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61,
	0x67, 0x75, 0x72, 0x75, 0x2f, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_routegrpc_proto_rawDescOnce sync.Once
	file_routegrpc_proto_rawDescData = file_routegrpc_proto_rawDesc
)

func file_routegrpc_proto_rawDescGZIP() []byte {
	file_routegrpc_proto_rawDescOnce.Do(func() {
		file_routegrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_routegrpc_proto_rawDescData)
	})
	return file_routegrpc_proto_rawDescData
}

var file_routegrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_routegrpc_proto_goTypes = []any{
	(*Crumb)(nil),  // 0: crumbdb.Crumb
	(*Point)(nil),  // 1: crumbdb.Point
	(*Id)(nil),     // 2: crumbdb.Id
	(*Status)(nil), // 3: crumbdb.Status
}
var file_routegrpc_proto_depIdxs = []int32{
	1, // 0: crumbdb.Crumb.location:type_name -> crumbdb.Point
	0, // 1: crumbdb.CrumbDB.Create:input_type -> crumbdb.Crumb
	1, // 2: crumbdb.CrumbDB.GetCrumbs:input_type -> crumbdb.Point
	0, // 3: crumbdb.CrumbDB.Update:input_type -> crumbdb.Crumb
	2, // 4: crumbdb.CrumbDB.Delete:input_type -> crumbdb.Id
	2, // 5: crumbdb.CrumbDB.Create:output_type -> crumbdb.Id
	0, // 6: crumbdb.CrumbDB.GetCrumbs:output_type -> crumbdb.Crumb
	2, // 7: crumbdb.CrumbDB.Update:output_type -> crumbdb.Id
	2, // 8: crumbdb.CrumbDB.Delete:output_type -> crumbdb.Id
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_routegrpc_proto_init() }
func file_routegrpc_proto_init() {
	if File_routegrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_routegrpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Crumb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routegrpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routegrpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routegrpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_routegrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routegrpc_proto_goTypes,
		DependencyIndexes: file_routegrpc_proto_depIdxs,
		MessageInfos:      file_routegrpc_proto_msgTypes,
	}.Build()
	File_routegrpc_proto = out.File
	file_routegrpc_proto_rawDesc = nil
	file_routegrpc_proto_goTypes = nil
	file_routegrpc_proto_depIdxs = nil
}
