name: crumbdb_service
port: 50051
loglevel: DEBUG
database:
  host: crumbdb 
  port: 27017 
  name: horus
  timeout: 5s
  collection: crumbs
  options:
    setstrict: true
    setdeprecationerrors: true
metrics:
  port: 52112
    
