service_name: crumbdb_service
port: 50051
loglevel: DEBUG
database:
  host: crumbdb 
  port: 27017 
  database_name: horus
  timeout: 5s
  ping_interval: 5s
  collection: crumbs
  options:
    setstrict: true
    setdeprecationerrors: true
metrics:
  port: 52112
    
