// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: follower.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Follow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: bson:"userId,omitempty" validate:"required"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"userId,omitempty" validate:"required"`
	// @gotags: bson:"followerUserId,omitempty" validate:"required"
	FollowerId    string `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty" bson:"followerUserId,omitempty" validate:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow) Reset() {
	*x = Follow{}
	mi := &file_follower_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow) ProtoMessage() {}

func (x *Follow) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow.ProtoReflect.Descriptor instead.
func (*Follow) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{0}
}

func (x *Follow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Follow) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_follower_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_follower_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_follower_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_follower_proto_rawDescGZIP(), []int{3}
}

func (x *GetFollowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFollowersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_follower_proto protoreflect.FileDescriptor

const file_follower_proto_rawDesc = "" +
	"\n" +
	"\x0efollower.proto\x12\n" +
	"followerdb\"9\n" +
	"\x06Follow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\tR\n" +
	"followerId\"\x1a\n" +
	"\x02Id\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1e\n" +
	"\x06Status\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"]\n" +
	"\x13GetFollowersRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize2\xb4\x01\n" +
	"\n" +
	"FollowerDB\x12/\n" +
	"\tAddFollow\x12\x12.followerdb.Follow\x1a\x0e.followerdb.Id\x12A\n" +
	"\fGetFollowers\x12\x1f.followerdb.GetFollowersRequest\x1a\x0e.followerdb.Id0\x01\x122\n" +
	"\bUnfollow\x12\x12.followerdb.Follow\x1a\x12.followerdb.StatusB;Z9github.com/haguru/horus/followerdb/internal/routes/protosb\x06proto3"

var (
	file_follower_proto_rawDescOnce sync.Once
	file_follower_proto_rawDescData []byte
)

func file_follower_proto_rawDescGZIP() []byte {
	file_follower_proto_rawDescOnce.Do(func() {
		file_follower_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follower_proto_rawDesc), len(file_follower_proto_rawDesc)))
	})
	return file_follower_proto_rawDescData
}

var file_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_follower_proto_goTypes = []any{
	(*Follow)(nil),              // 0: followerdb.Follow
	(*Id)(nil),                  // 1: followerdb.Id
	(*Status)(nil),              // 2: followerdb.Status
	(*GetFollowersRequest)(nil), // 3: followerdb.GetFollowersRequest
}
var file_follower_proto_depIdxs = []int32{
	0, // 0: followerdb.FollowerDB.AddFollow:input_type -> followerdb.Follow
	3, // 1: followerdb.FollowerDB.GetFollowers:input_type -> followerdb.GetFollowersRequest
	0, // 2: followerdb.FollowerDB.Unfollow:input_type -> followerdb.Follow
	1, // 3: followerdb.FollowerDB.AddFollow:output_type -> followerdb.Id
	1, // 4: followerdb.FollowerDB.GetFollowers:output_type -> followerdb.Id
	2, // 5: followerdb.FollowerDB.Unfollow:output_type -> followerdb.Status
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_follower_proto_init() }
func file_follower_proto_init() {
	if File_follower_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follower_proto_rawDesc), len(file_follower_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follower_proto_goTypes,
		DependencyIndexes: file_follower_proto_depIdxs,
		MessageInfos:      file_follower_proto_msgTypes,
	}.Build()
	File_follower_proto = out.File
	file_follower_proto_goTypes = nil
	file_follower_proto_depIdxs = nil
}
