service_name: useracct_service
port: 50053
loglevel: DEBUG
database:
  host: useracctdb 
  port: 27017 
  database_name: horus
  timeout: 5s
  ping_interval: 5s
  collection: users
  options:
    setstrict: true
    setdeprecationerrors: true
metrics:
  port: 52112
