name: follower_service
port: 50055
loglevel: DEBUG
database:
  host: followerdb
  port: 27017 
  name: horus
  timeout: 5s
  ping_interval: 5s
  collection: users
  options:
    setstrict: true
    setdeprecationerrors: true
metrics:
  port: 52112
    
