name: useracctdb
port: 50055
loglevel: DEBUG
database:
  host: followerdb #mongodb://localhost:27017/?maxPoolSize=20&w=majority
  port: 27017 #50056
  name: horus
  collection: users
  options:
    setstrict: true
    setdeprecationerrors: true
    
